listen:
  address: 0.0.0.0
  port: 8080
logs:
  target: /dev/stdout
  level: debug
  format: json
repositories:
  - prefix: "rocks"
    storage: nexus
    allow_rewrite: true
    allowed_file_extensions:
      - ".rockspec"
      - "rock"

storages:
  test:
    type: fs
    dir: .src
  nexus:
    type: nexus
    address: http://admin:admin@localhost:8081/
    repository: rocks
    index_update_interval: 15s
    request_timeout: 1s




