listen:
  address: 0.0.0.0
  port: 8080
logs:
  target: /dev/stdout
  level: debug
  format: json
repositories:
  - prefix: "rocks"
    storage: fs
    allow_rewrite: true
    allowed_file_extensions:
      - ".rockspec"
      - "rock"

storages:
  fs:
    type: fs
    dir: .src
# nexus storage configuration for communicating by default
#  nexus:
#    type: nexus
#    address: http://admin:admin@localhost:8081/
#    repository: rocks
#    index_update_interval: 15s
#    request_timeout: 1s




